'use strict';

/**
 * @fontsource-specific shaping for the vendoring engine (issue #68 Part B).
 *
 * The engine (scripts/lib/vendor.js) is font-agnostic — it fetches/verifies/
 * writes bytes. The font-specific bits live here and are wired in through the
 * manifest: which woff2 a family contributes, and how to assemble the
 * normalized @font-face CSS the decks <link>.
 *
 * We do NOT ship @fontsource's CSS verbatim — its index.css pulls every weight
 * and every subset (cyrillic, greek, vietnamese…). Instead we filter the
 * package's own per-weight CSS down to the requested subsets, reusing upstream's
 * exact font-family / font-weight / font-display / unicode-range so the result
 * stays byte-faithful to what Google served, and drop only (a) the subsets we
 * don't want and (b) the .woff fallback (we vendor woff2 only — every target
 * browser supports it).
 */

// The per-(weight × subset) woff2 a family contributes, as logical tarball
// paths (relative to the package's `files/`). @fontsource names them
// `<id>-<subset>-<weight>-normal.woff2` (id = the unscoped package name).
function fontFiles(id, weights, subsets) {
  const files = [];
  for (const w of weights) {
    for (const s of subsets) {
      files.push(`files/${id}-${s}-${w}-normal.woff2`);
    }
  }
  return files;
}

// Assemble the normalized CSS for one family from @fontsource's per-weight CSS
// members. Returns a deterministic string (no timestamps) so its sha256 is a
// stable integrity pin like any other vendored file.
async function buildFontCss(source, { id, family, weights, subsets }) {
  const want = new Set(fontFiles(id, weights, subsets).map((p) => p.replace(/^files\//, '')));
  const blockRe = /\/\*([\s\S]*?)\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
  const woffFallback = /,\s*url\(\.\/files\/[^)]+\.woff\)\s+format\(\s*['"]woff['"]\s*\)/g;
  const seen = new Set();
  const blocks = [];

  // Iterate weights in the order given, and keep each weight file's blocks in
  // upstream order. @fontsource lists latin-ext before latin; the two ranges
  // overlap on the combining marks U+0304/0308/0329, where the LAST matching
  // @font-face wins — so preserving upstream order (latin last) keeps Google's
  // exact glyph selection.
  for (const w of weights) {
    const css = (await source.bytes(`${w}.css`)).toString('utf8');
    for (const m of css.matchAll(blockRe)) {
      const url = m[2].match(/url\(\.\/files\/([^)]+\.woff2)\)/);
      if (!url || !want.has(url[1])) continue;
      seen.add(url[1]);
      blocks.push(`/*${m[1]}*/\n${m[2].replace(woffFallback, '')}`);
    }
  }

  const missing = [...want].filter((f) => !seen.has(f));
  if (missing.length) {
    throw new Error(`@fontsource/${id}: requested faces absent from upstream CSS: ${missing.join(', ')}`);
  }

  const header =
    `/*! ${family} — self-hosted from @fontsource/${id}. ` +
    `Subsets: ${subsets.join(', ')}. Weights: ${weights.join(', ')}. ` +
    `Generated by scripts/vendor.js (woff2-only); provenance in ../README.md. */\n\n`;
  return header + blocks.join('\n\n') + '\n';
}

module.exports = { fontFiles, buildFontCss };
